# Generated by Django 3.2.17 on 2023-02-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('total_rooms', models.IntegerField()),
            ],
        ),
    ]
