# Generated by Django 3.2.17 on 2023-02-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='user_id',
        ),
    ]
