# Generated by Django 3.2.17 on 2023-02-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_count', models.IntegerField(default=1)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel.hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel.room')),
            ],
        ),
    ]
