# Generated by Django 3.2.17 on 2023-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCEL', 'Cancel')], default='ACTIVE', max_length=6),
        ),
    ]
